# Generated by Django 4.2.7 on 2023-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
