# Generated by Django 4.2.7 on 2023-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodule",
            name="quantity_on_hand",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customusermodule",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
