# Generated by Django 4.2.7 on 2023-11-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_customusermodule_quantity_on_hand_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserpermission",
            name="name",
        ),
        migrations.AddField(
            model_name="customuserpermission",
            name="role",
            field=models.ManyToManyField(
                related_name="permissions", to="user.customuserrole"
            ),
        ),
    ]
