# Generated by Django 4.2.7 on 2023-11-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_rename_name_customuserrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
