# Generated by Django 4.2.7 on 2023-11-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_customusermodule_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserrole",
            name="modules",
        ),
    ]
